/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/congestion': RouteRecordInfo<
      '/congestion',
      '/congestion',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hi/[name]': RouteRecordInfo<
      '/hi/[name]',
      '/hi/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/hotspot': RouteRecordInfo<
      '/hotspot',
      '/hotspot',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hotspot-map': RouteRecordInfo<
      '/hotspot-map',
      '/hotspot-map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/map': RouteRecordInfo<
      '/map',
      '/map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/network-status': RouteRecordInfo<
      '/network-status',
      '/network-status',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/road-status': RouteRecordInfo<
      '/road-status',
      '/road-status',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/trajectory-map': RouteRecordInfo<
      '/trajectory-map',
      '/trajectory-map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/trip-features': RouteRecordInfo<
      '/trip-features',
      '/trip-features',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/congestion.vue': {
      routes:
        | '/congestion'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/pages/hi/[name].vue': {
      routes:
        | '/hi/[name]'
      views:
        | never
    }
    'src/pages/hotspot.vue': {
      routes:
        | '/hotspot'
      views:
        | never
    }
    'src/pages/hotspot-map.vue': {
      routes:
        | '/hotspot-map'
      views:
        | never
    }
    'src/pages/map.vue': {
      routes:
        | '/map'
      views:
        | never
    }
    'src/pages/network-status.vue': {
      routes:
        | '/network-status'
      views:
        | never
    }
    'src/pages/road-status.vue': {
      routes:
        | '/road-status'
      views:
        | never
    }
    'src/pages/trajectory-map.vue': {
      routes:
        | '/trajectory-map'
      views:
        | never
    }
    'src/pages/trip-features.vue': {
      routes:
        | '/trip-features'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
